export const DEFAULT_KPIS = {
  sales: [
    {
      id: 'greeting',
      name: 'Professional Greeting',
      weight: 15,
      criteria: 'Agent introduces company and self within first 10 seconds',
      keywords: ['hello', 'thank you for calling', 'my name'],
      required: true,
    },
    {
      id: 'qualification',
      name: 'Lead Qualification',
      weight: 25,
      criteria: 'Agent asks discovery questions about needs, timeline, and budget',
      keywords: ['looking for', 'help with', 'timeline', 'budget', 'need'],
      required: true,
    },
    {
      id: 'objection_handling',
      name: 'Objection Handling',
      weight: 25,
      criteria: 'Agent acknowledges and responds to caller objections',
      keywords: ['understand', 'appreciate', 'option', 'flexible'],
      required: true,
    },
    {
      id: 'cta',
      name: 'Call-to-Action',
      weight: 20,
      criteria: 'Agent proposes clear next step before ending call',
      keywords: ['schedule', 'book', 'appointment', 'next step', 'follow up'],
      required: true,
    },
    {
      id: 'compliance',
      name: 'Compliance',
      weight: 15,
      criteria: 'No unapproved guarantee or misleading statements',
      keywords: [],
      required: true,
    },
  ],
  support: [
    {
      id: 'greeting',
      name: 'Professional Greeting',
      weight: 20,
      criteria: 'Agent greets and confirms caller identity',
      keywords: ['hello', 'how can i help', 'thank you for calling'],
      required: true,
    },
    {
      id: 'qualification',
      name: 'Issue Identification',
      weight: 30,
      criteria: 'Agent identifies the core issue quickly',
      keywords: ['issue', 'problem', 'help with', 'experiencing'],
      required: true,
    },
    {
      id: 'cta',
      name: 'Resolution / Next Step',
      weight: 30,
      criteria: 'Agent confirms resolution or sets follow-up',
      keywords: ['resolved', 'ticket', 'follow up', 'email you'],
      required: true,
    },
    {
      id: 'compliance',
      name: 'Compliance',
      weight: 20,
      criteria: 'No unauthorized promises about refunds or timelines',
      keywords: [],
      required: true,
    },
  ],
  booking: [
    {
      id: 'greeting',
      name: 'Warm Greeting',
      weight: 15,
      criteria: 'Friendly branded opening',
      keywords: ['hello', 'welcome', 'thank you for calling'],
      required: true,
    },
    {
      id: 'qualification',
      name: 'Availability Check',
      weight: 25,
      criteria: 'Agent confirms service type and preferred times',
      keywords: ['available', 'prefer', 'date', 'time', 'appointment'],
      required: true,
    },
    {
      id: 'cta',
      name: 'Booking Confirmation',
      weight: 35,
      criteria: 'Agent confirms appointment details',
      keywords: ['booked', 'confirmed', 'see you', 'appointment'],
      required: true,
    },
    {
      id: 'compliance',
      name: 'Compliance',
      weight: 25,
      criteria: 'Cancellation policy mentioned when relevant',
      keywords: ['cancel', 'policy', 'reschedule'],
      required: false,
    },
  ],
};

export const DEMO_AGENTS = [
  {
    id: 'agent_sales_demo',
    name: 'Sales Qualifier AI',
    location_id: 'loc_sandbox_001',
    script_summary: 'Qualify inbound leads, handle pricing objections, book demos.',
    agent_type: 'sales',
  },
  {
    id: 'agent_support_demo',
    name: 'Support Triage AI',
    location_id: 'loc_sandbox_001',
    script_summary: 'Triage support calls, create tickets, escalate when frustrated.',
    agent_type: 'support',
  },
  {
    id: 'agent_booking_demo',
    name: 'Appointment Booker AI',
    location_id: 'loc_sandbox_001',
    script_summary: 'Book appointments for dental consultations.',
    agent_type: 'booking',
  },
];

export const DEMO_CALLS = [
  {
    agentId: 'agent_sales_demo',
    contactName: 'Sarah Mitchell',
    durationSeconds: 186,
    outcome: 'completed',
    summary: 'Lead interested but hesitant on pricing. Demo not booked.',
    transcript: [
      { role: 'agent', text: 'Hello, thank you for calling Acme Solutions! My name is Alex. How can I help you today?', timestamp: 0 },
      { role: 'caller', text: 'Hi, I saw your ad online. I need help with automating our sales follow-ups.', timestamp: 8 },
      { role: 'agent', text: 'Great! We specialize in sales automation. Can you tell me a bit about your current process?', timestamp: 15 },
      { role: 'caller', text: 'We have about 50 leads a week and our team can\'t keep up with follow-ups.', timestamp: 22 },
      { role: 'agent', text: 'That sounds like a perfect fit. Our platform handles automated follow-ups via email and SMS.', timestamp: 30 },
      { role: 'caller', text: 'Sounds good but honestly it seems too expensive for us right now.', timestamp: 40 },
      { role: 'agent', text: 'I see. Well, we have different plans available.', timestamp: 48 },
      { role: 'caller', text: 'I\'ll think about it and maybe call back later.', timestamp: 55 },
      { role: 'agent', text: 'Sure, feel free to reach out anytime. Have a great day!', timestamp: 62 },
    ],
  },
  {
    agentId: 'agent_sales_demo',
    contactName: 'James Chen',
    durationSeconds: 245,
    outcome: 'completed',
    summary: 'Successful qualification and demo booked for Thursday.',
    transcript: [
      { role: 'agent', text: 'Hello, thank you for calling Acme Solutions! This is Alex. How may I assist you?', timestamp: 0 },
      { role: 'caller', text: 'I\'m looking for a CRM integration for our marketing agency.', timestamp: 7 },
      { role: 'agent', text: 'I\'d love to help. What\'s your timeline for implementing a solution?', timestamp: 14 },
      { role: 'caller', text: 'We need something within the next month. Budget is around five thousand.', timestamp: 22 },
      { role: 'agent', text: 'Perfect. I understand budget is important — many agencies see ROI within 90 days. Would a quick demo help?', timestamp: 32 },
      { role: 'caller', text: 'Yes, Thursday afternoon works for me.', timestamp: 42 },
      { role: 'agent', text: 'Excellent! I\'ll schedule a 15-minute demo for Thursday at 2pm. I\'ll send a confirmation email.', timestamp: 50 },
    ],
  },
  {
    agentId: 'agent_support_demo',
    contactName: 'Maria Lopez',
    durationSeconds: 120,
    outcome: 'completed',
    summary: 'Frustrated caller requesting human agent.',
    transcript: [
      { role: 'agent', text: 'Hello, thank you for calling support. How can I help you today?', timestamp: 0 },
      { role: 'caller', text: 'My account has been locked for three days and nobody has helped me!', timestamp: 6 },
      { role: 'agent', text: 'I can look into that. Can you provide your email address?', timestamp: 14 },
      { role: 'caller', text: 'I already did that twice! This is so frustrating. I want to speak to a real person.', timestamp: 22 },
      { role: 'agent', text: 'I understand. Let me check your account status.', timestamp: 30 },
      { role: 'caller', text: 'This doesn\'t work. Just stop calling me about this.', timestamp: 38 },
    ],
  },
  {
    agentId: 'agent_support_demo',
    contactName: 'Tom Bradley',
    durationSeconds: 95,
    outcome: 'completed',
    summary: 'Password reset resolved successfully.',
    transcript: [
      { role: 'agent', text: 'Hi, thank you for calling support. My name is Sam. What issue are you experiencing?', timestamp: 0 },
      { role: 'caller', text: 'I can\'t log into my dashboard. I forgot my password.', timestamp: 8 },
      { role: 'agent', text: 'No problem. I\'ll send a password reset link to your email right now.', timestamp: 15 },
      { role: 'caller', text: 'Got it, that worked. Thanks!', timestamp: 28 },
      { role: 'agent', text: 'Glad it\'s resolved! I\'ll follow up via email with security tips. Have a great day!', timestamp: 35 },
    ],
  },
  {
    agentId: 'agent_booking_demo',
    contactName: 'Emily Watson',
    durationSeconds: 78,
    outcome: 'completed',
    summary: 'Appointment booked but cancellation policy not mentioned.',
    transcript: [
      { role: 'agent', text: 'Welcome to Bright Smile Dental! How can I help you today?', timestamp: 0 },
      { role: 'caller', text: 'I\'d like to book a cleaning appointment for next week.', timestamp: 6 },
      { role: 'agent', text: 'I have availability on Tuesday at 10am or Wednesday at 3pm. Which do you prefer?', timestamp: 12 },
      { role: 'caller', text: 'Tuesday at 10 works great.', timestamp: 20 },
      { role: 'agent', text: 'You\'re all set! Your appointment is confirmed for Tuesday at 10am.', timestamp: 26 },
    ],
  },
  {
    agentId: 'agent_sales_demo',
    contactName: 'David Park',
    durationSeconds: 160,
    outcome: 'completed',
    summary: 'Caller confused about product features.',
    transcript: [
      { role: 'agent', text: 'Hello! Thanks for calling. This is Alex from Acme Solutions.', timestamp: 0 },
      { role: 'caller', text: 'What exactly does your product do? I don\'t understand from your website.', timestamp: 8 },
      { role: 'agent', text: 'We offer a comprehensive suite of business automation tools.', timestamp: 16 },
      { role: 'caller', text: 'What do you mean? Can you repeat that in simpler terms?', timestamp: 24 },
      { role: 'agent', text: 'Sure — we help automate repetitive tasks in your business workflow.', timestamp: 32 },
      { role: 'caller', text: 'OK that makes more sense. What\'s the pricing?', timestamp: 40 },
      { role: 'agent', text: 'Plans start at $99/month. I guarantee you\'ll see 100% improvement in productivity.', timestamp: 48 },
      { role: 'caller', text: 'That guarantee sounds too good to be true...', timestamp: 56 },
    ],
  },
];
